
# Machine Learning Zoomcamp
## 1.7 Introduction to NumPy

Plan:

- Creating arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
    - Comparison operations
    - Logical operations
- Summarizing operations


In [ ]:
import numpy as np

In [3]:
np

<module 'numpy' from '/Users/ifabela/Documents/iocode/DataTalks_club/ml-course-datatalksclub/.venv/lib/python3.14/site-packages/numpy/__init__.py'>

## Creating Arrays

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,5,7,12])
a # numpy-array

array([ 1,  2,  3,  5,  7, 12])

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

##  Multi-dimensional arrays

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0,1] = 20

In [23]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [35]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [ ]:
np.random.rand(5, 2) # [X, Y] dimension, from 0 to 1 distribution

array([[0.80788371, 0.49528861],
       [0.02534008, 0.96956127],
       [0.50259036, 0.69529539],
       [0.38976789, 0.60399044],
       [0.75423031, 0.26925713]])

In [ ]:
np.random.seed(2)
np.random.randn(5, 2) # [X, Y] dimension, from 0 to 1 n-distribution

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [38]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2)) # random-integer

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
a + 1

array([1, 2, 3, 4, 5])

In [42]:
a * 2

array([0, 2, 4, 6, 8])

In [49]:
b = ((10 + (a * 2)) ** 2) / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [50]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [51]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [54]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [53]:
a > b

array([False, False,  True,  True,  True])

In [55]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [59]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.min()

np.int64(0)

In [61]:
a.max()

np.int64(4)

In [62]:
a.sum()

np.int64(10)

In [ ]:
a.mean() # Mean (average) value

np.float64(2.0)

In [ ]:
a.std() # Standard deviation

np.float64(1.4142135623730951)